proja: proja.o
	ld -o proja proja.o
proja.o: proja.asm 
	nasm -f elf64 -g proja.asm
projataketwo: projataketwo.o
	ld -o projataketwo projataketwo.o
projataketwo.o: projataketwo.asm
	nasm -f elf64 -g projataketwo.asm
